import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ImagePlus, Link as LinkIcon, Plus, Trash2, UtensilsCrossed } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

export default function MenuBuilder() {
  const [, params] = useRoute("/app/menu/:id"); const restaurantId = Number(params?.id); const [, setLocation] = useLocation(); const utils = trpc.useUtils();
  const restaurant = trpc.restaurant.get.useQuery({ id: restaurantId }, { enabled: Number.isFinite(restaurantId) }); const categories = trpc.category.list.useQuery({ restaurantId }, { enabled: Number.isFinite(restaurantId) }); const items = trpc.menu.list.useQuery({ restaurantId }, { enabled: Number.isFinite(restaurantId) });
  const [categoryName, setCategoryName] = useState(""); const [categoryDescription, setCategoryDescription] = useState(""); const [itemName, setItemName] = useState(""); const [itemDescription, setItemDescription] = useState(""); const [price, setPrice] = useState(""); const [categoryId, setCategoryId] = useState<number | null>(null); const [available, setAvailable] = useState(true); const [imageUrl, setImageUrl] = useState("");
  const categoryCreate = trpc.category.create.useMutation({ onSuccess: () => { utils.category.list.invalidate({ restaurantId }); setCategoryName(""); setCategoryDescription(""); toast.success("Category added."); }, onError: error => toast.error(error.message) });
  const categoryDelete = trpc.category.delete.useMutation({ onSuccess: () => { utils.category.list.invalidate({ restaurantId }); utils.menu.list.invalidate({ restaurantId }); toast.success("Category removed."); }, onError: error => toast.error(error.message) });
  const itemCreate = trpc.menu.create.useMutation({ onSuccess: () => { utils.menu.list.invalidate({ restaurantId }); setItemName(""); setItemDescription(""); setPrice(""); setImageUrl(""); toast.success("Menu item published."); }, onError: error => toast.error(error.message) });
  const itemUpdate = trpc.menu.update.useMutation({ onSuccess: () => utils.menu.list.invalidate({ restaurantId }), onError: error => toast.error(error.message) });
  const itemDelete = trpc.menu.delete.useMutation({ onSuccess: () => { utils.menu.list.invalidate({ restaurantId }); toast.success("Menu item removed."); }, onError: error => toast.error(error.message) });
  const upload = trpc.menu.uploadImage.useMutation({ onSuccess: stored => { setImageUrl(stored.url); toast.success("Image ready to attach."); }, onError: error => toast.error(error.message) });
  const submitCategory = (event: FormEvent) => { event.preventDefault(); categoryCreate.mutate({ restaurantId, name: categoryName, description: categoryDescription }); };
  const submitItem = (event: FormEvent) => { event.preventDefault(); const selected = categoryId ?? categories.data?.[0]?.id; if (!selected) return toast.error("Create a category before adding a menu item."); itemCreate.mutate({ restaurantId, categoryId: selected, name: itemName, description: itemDescription, price: Number(price), imageUrl, isAvailable: available }); };
  const chooseImage = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type)) return toast.error("Use a JPG, PNG, or WebP image."); if (file.size > 5_000_000) return toast.error("Choose an image smaller than 5 MB."); const reader = new FileReader(); reader.onload = () => upload.mutate({ filename: file.name, contentType: file.type as "image/jpeg" | "image/png" | "image/webp", dataUrl: String(reader.result) }); reader.readAsDataURL(file); };
  const grouped = (categories.data ?? []).map(category => ({ category, entries: items.data?.filter(item => item.categoryId === category.id) ?? [] }));
  if (!Number.isFinite(restaurantId)) return <DashboardLayout><p>Restaurant not found.</p></DashboardLayout>;
  return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><button onClick={() => setLocation("/app/restaurants")} className="text-sm text-[#766b5d] hover:text-[#201d19]">← Restaurants</button><p className="eyebrow mt-5 text-[#8b7560]">Menu builder</p><h1 className="mt-3 font-display text-4xl tracking-[-0.045em] text-[#201d19] sm:text-5xl">{restaurant.data?.name ?? "Your menu"}</h1></div><Button onClick={() => setLocation(`/app/qr/${restaurantId}`)} variant="outline" className="rounded-full border-[#d7cfc3]"><LinkIcon className="mr-2 h-4 w-4" />Open QR studio</Button></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><div className="space-y-6"><form onSubmit={submitCategory} className="rounded-3xl bg-[#e9ddce] p-6"><div className="flex items-center justify-between"><h2 className="font-display text-2xl text-[#201d19]">Add a category</h2><Plus className="h-5 w-5 text-[#795f4a]" /></div><label className="label mt-6" htmlFor="category-name">Category name</label><Input id="category-name" required minLength={2} value={categoryName} onChange={event => setCategoryName(event.target.value)} placeholder="Starters, mains, desserts…" className="field bg-white/80" /><label className="label mt-4" htmlFor="category-description">Description <span className="font-normal normal-case text-[#8a7e70]">optional</span></label><Textarea id="category-description" value={categoryDescription} onChange={event => setCategoryDescription(event.target.value)} placeholder="A short note for guests" className="field min-h-20 bg-white/80" /><Button type="submit" disabled={categoryCreate.isPending} className="mt-5 rounded-full bg-[#201d19] text-white hover:bg-[#3a342e]">{categoryCreate.isPending ? "Adding…" : "Add category"}</Button></form>
      <form onSubmit={submitItem} className="rounded-3xl border border-[#ded5ca] bg-[#fbf9f5] p-6"><div className="flex items-center justify-between"><h2 className="font-display text-2xl text-[#201d19]">Add a menu item</h2><UtensilsCrossed className="h-5 w-5 text-[#ed5739]" /></div><label className="label mt-6" htmlFor="item-name">Dish name</label><Input id="item-name" required minLength={2} value={itemName} onChange={event => setItemName(event.target.value)} placeholder="e.g. Charred paneer tikka" className="field" /><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><label className="label" htmlFor="item-price">Price (₹)</label><Input id="item-price" type="number" min="0" step="0.01" required value={price} onChange={event => setPrice(event.target.value)} placeholder="320" className="field" /></div><div><label className="label" htmlFor="item-category">Category</label><select id="item-category" value={categoryId ?? categories.data?.[0]?.id ?? ""} onChange={event => setCategoryId(Number(event.target.value))} className="field h-10 w-full rounded-md bg-transparent px-3 text-sm outline-none"><option value="" disabled>Choose category</option>{categories.data?.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div></div><label className="label mt-4" htmlFor="item-description">Description</label><Textarea id="item-description" value={itemDescription} onChange={event => setItemDescription(event.target.value)} placeholder="A clear, appetizing description." className="field min-h-20" /><div className="mt-4 flex items-center justify-between rounded-2xl bg-[#f0ebe3] p-4"><div><p className="text-sm font-semibold text-[#201d19]">Available now</p><p className="mt-1 text-xs text-[#756c61]">Hidden items never appear on the public menu.</p></div><Switch checked={available} onCheckedChange={setAvailable} /></div><div className="mt-4"><label className="label" htmlFor="item-image">Food image <span className="font-normal normal-case text-[#8a7e70]">optional</span></label><div className="flex items-center gap-3"><label htmlFor="item-image" className="inline-flex h-10 cursor-pointer items-center rounded-full border border-[#d5cbbc] bg-white px-4 text-sm font-medium text-[#201d19] transition hover:border-[#201d19]"><ImagePlus className="mr-2 h-4 w-4" />{upload.isPending ? "Uploading…" : "Upload image"}</label><input id="item-image" type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage} className="sr-only" />{imageUrl && <span className="text-xs text-[#64734c]">Image attached</span>}</div></div><Button type="submit" disabled={itemCreate.isPending || categories.data?.length === 0} className="mt-5 rounded-full bg-[#ed5739] text-white hover:bg-[#d94830]">{itemCreate.isPending ? "Publishing…" : "Publish menu item"}</Button>{categories.data?.length === 0 && <p className="mt-3 text-xs text-[#aa4734]">Add a category before publishing an item.</p>}</form></div>
      <div className="space-y-5">{categories.isLoading ? <div className="h-72 animate-pulse rounded-3xl bg-[#e6dfd6]" /> : grouped.length === 0 ? <div className="grid min-h-80 place-items-center rounded-3xl border border-dashed border-[#d4c9ba] bg-[#fbf9f5] p-8 text-center"><div><UtensilsCrossed className="mx-auto h-7 w-7 text-[#a48e75]" /><h2 className="mt-5 font-display text-3xl text-[#201d19]">Start with a category.</h2><p className="mt-2 text-sm text-[#6e665d]">It will keep your public menu calm and easy to scan.</p></div></div> : grouped.map(({ category, entries }) => <section key={category.id} className="rounded-3xl border border-[#e2dad0] bg-[#fbf9f5] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-[#8b7560]">Category</p><h2 className="mt-2 font-display text-3xl text-[#201d19]">{category.name}</h2>{category.description && <p className="mt-2 text-sm text-[#746b60]">{category.description}</p>}</div><button onClick={() => { if (confirm(`Delete ${category.name} and its menu items?`)) categoryDelete.mutate({ id: category.id }); }} aria-label={`Delete ${category.name}`} className="rounded-xl p-2 text-[#a29484] transition hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div><div className="mt-5 divide-y divide-[#e8e1d7]">{entries.length === 0 ? <p className="py-5 text-sm text-[#887e72]">No published dishes in this category yet.</p> : entries.map(item => <div key={item.id} className="flex gap-4 py-4 first:pt-0"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-2xl bg-[#e9e0d5]">{item.imageUrl ? <img src={item.imageUrl} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><UtensilsCrossed className="h-5 w-5 text-[#a79279]" /></div>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[#201d19]">{item.name}</p><p className="mt-1 text-sm text-[#73695d]">{item.description || "No description"}</p></div><span className="font-display text-xl text-[#201d19]">₹{item.price.toFixed(2).replace(/\.00$/, "")}</span></div><div className="mt-3 flex items-center gap-3"><button onClick={() => itemUpdate.mutate({ id: item.id, isAvailable: !item.isAvailable })} className={`rounded-full px-3 py-1 text-xs font-semibold ${item.isAvailable ? "bg-[#e1ead8] text-[#4a6234]" : "bg-[#efe5dc] text-[#8c543f]"}`}>{item.isAvailable ? "Available" : "Hidden"}</button><button onClick={() => { if (confirm(`Remove ${item.name}?`)) itemDelete.mutate({ id: item.id }); }} className="text-xs font-semibold text-[#9a5845] hover:text-red-700">Remove</button></div></div></div>)}</div></section>)}</div></div></div></DashboardLayout>;
}
