import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Check, Copy, Download, ExternalLink, Printer, QrCode } from "lucide-react";
import QRCode from "qrcode";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

export default function QRStudio() {
  const [, params] = useRoute("/app/qr/:id"); const restaurantId = Number(params?.id); const restaurant = trpc.restaurant.get.useQuery({ id: restaurantId }, { enabled: Number.isFinite(restaurantId) }); const [, setLocation] = useLocation(); const [image, setImage] = useState(""); const [copied, setCopied] = useState(false);
  const publicUrl = restaurant.data ? `${window.location.origin}/menu/${restaurant.data.slug}` : "";
  useEffect(() => { if (publicUrl) QRCode.toDataURL(publicUrl, { width: 640, margin: 1, color: { dark: "#201d19", light: "#f8f3ea" } }).then(setImage).catch(() => toast.error("QR image could not be prepared.")); }, [publicUrl]);
  const copy = async () => { try { await navigator.clipboard.writeText(publicUrl); setCopied(true); toast.success("Menu link copied."); setTimeout(() => setCopied(false), 1800); } catch { toast.error("Copy is unavailable here. Select the menu address below."); } };
  const download = () => { const anchor = document.createElement("a"); anchor.href = image; anchor.download = `${restaurant.data?.slug ?? "qrserve-menu"}-qr.png`; anchor.click(); };
  if (!Number.isFinite(restaurantId)) return <DashboardLayout><p>Restaurant not found.</p></DashboardLayout>;
  return <DashboardLayout><div className="mx-auto max-w-5xl"><button onClick={() => setLocation(`/app/menu/${restaurantId}`)} className="text-sm text-[#766b5d] hover:text-[#201d19]">← Back to menu builder</button><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#8b7560]">QR studio</p><h1 className="mt-3 font-display text-4xl tracking-[-0.045em] text-[#201d19] sm:text-5xl">A menu in every scan.</h1></div>{restaurant.data && <a href={`/menu/${restaurant.data.slug}`} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center justify-center rounded-full border border-[#d7cfc3] px-4 text-sm font-medium text-[#201d19] transition hover:border-[#201d19]"><ExternalLink className="mr-2 h-4 w-4" />Open public menu</a>}</div><div className="qr-print-card mt-8 grid overflow-hidden rounded-[2rem] border border-[#ded5ca] bg-[#fbf9f5] lg:grid-cols-[0.9fr_1.1fr]"><div className="grid place-items-center bg-[#e8dccd] p-8 sm:p-12">{image ? <img src={image} alt={`QR code for ${restaurant.data?.name ?? "restaurant"} public menu`} className="w-full max-w-72 rounded-2xl bg-[#f8f3ea] p-3 shadow-[0_14px_40px_rgba(68,46,27,0.16)]" /> : <div className="grid h-72 w-72 place-items-center rounded-2xl bg-[#f8f3ea]"><QrCode className="h-10 w-10 animate-pulse text-[#9c8d7b]" /></div>}</div><div className="p-7 sm:p-10"><p className="eyebrow text-[#8b7560]">{restaurant.data?.location ?? "Preparing destination"}</p><h2 className="mt-3 font-display text-4xl text-[#201d19]">{restaurant.data?.name ?? "Your restaurant"}</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[#71685e]">Place this code where guests make their decision. The destination always reflects your latest published menu.</p><p className="mt-7 text-xs font-semibold uppercase tracking-[0.16em] text-[#8b7560]">Public menu address</p><p className="mt-2 break-all rounded-xl bg-[#f0ebe3] p-3 font-mono text-xs leading-5 text-[#51483f]">{publicUrl || "Generating link…"}</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={copy} disabled={!publicUrl} className="rounded-full bg-[#201d19] text-white hover:bg-[#3a342e]">{copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}{copied ? "Copied" : "Copy link"}</Button><Button onClick={download} disabled={!image} variant="outline" className="rounded-full border-[#d7cfc3]"><Download className="mr-2 h-4 w-4" />Download QR</Button><Button onClick={() => window.print()} disabled={!image} variant="outline" className="rounded-full border-[#d7cfc3]"><Printer className="mr-2 h-4 w-4" />Print card</Button></div></div></div></div></DashboardLayout>;
}
