import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { MapPin, Pencil, Plus, QrCode, Trash2, UtensilsCrossed } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function Restaurants() {
  const [showForm, setShowForm] = useState(false);
  const [name, setName] = useState(""); const [location, setLocationText] = useState(""); const [description, setDescription] = useState("");
  const [editingId, setEditingId] = useState<number | null>(null);
  const restaurants = trpc.restaurant.list.useQuery(); const utils = trpc.useUtils(); const [, setLocation] = useLocation();
  const create = trpc.restaurant.create.useMutation({ onSuccess: restaurant => { utils.restaurant.list.invalidate(); toast.success("Client venue created. Let’s prepare its menu."); setLocation(`/app/menu/${restaurant.id}`); }, onError: error => toast.error(error.message) });
  const update = trpc.restaurant.update.useMutation({ onSuccess: () => { utils.restaurant.list.invalidate(); setShowForm(false); setEditingId(null); setName(""); setLocationText(""); setDescription(""); toast.success("Client venue details saved."); }, onError: error => toast.error(error.message) });
  const remove = trpc.restaurant.delete.useMutation({ onSuccess: () => { utils.restaurant.list.invalidate(); toast.success("Client venue removed."); }, onError: error => toast.error(error.message) });
  const resetForm = () => { setShowForm(false); setEditingId(null); setName(""); setLocationText(""); setDescription(""); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (editingId) update.mutate({ id: editingId, name, location, description }); else create.mutate({ name, location, description }); };
  return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#8b7560]">Client venues</p><h1 className="mt-3 font-display text-4xl tracking-[-0.045em] text-[#201d19] sm:text-5xl">The places you set up and support.</h1></div><Button onClick={() => setShowForm(value => !value)} className="rounded-full bg-[#ed5739] text-white hover:bg-[#d94830]"><Plus className="mr-2 h-4 w-4" />Add client venue</Button></div>
    {showForm && <form onSubmit={submit} className="mt-8 grid gap-4 rounded-[1.75rem] border border-[#ded4c7] bg-[#fbf9f5] p-6 sm:grid-cols-2 sm:p-8"><div className="sm:col-span-2"><label className="label" htmlFor="restaurant-name">Venue name</label><Input id="restaurant-name" value={name} onChange={event => setName(event.target.value)} required minLength={2} placeholder="e.g. Jamun Kitchen" className="field" /></div><div><label className="label" htmlFor="restaurant-location">Location</label><Input id="restaurant-location" value={location} onChange={event => setLocationText(event.target.value)} required minLength={2} placeholder="e.g. Bandra West, Mumbai" className="field" /></div><div><label className="label" htmlFor="restaurant-timezone">Menu timezone</label><Input id="restaurant-timezone" defaultValue="Asia/Kolkata" disabled className="field opacity-70" /></div><div className="sm:col-span-2"><label className="label" htmlFor="restaurant-description">Public venue description</label><Textarea id="restaurant-description" value={description} onChange={event => setDescription(event.target.value)} placeholder="A short description that guests will see after scanning." className="field min-h-24" /></div><div className="flex gap-3 sm:col-span-2"><Button type="submit" disabled={create.isPending || update.isPending} className="rounded-full bg-[#201d19] text-white hover:bg-[#3a342e]">{create.isPending || update.isPending ? "Saving…" : editingId ? "Save changes" : "Create client venue"}</Button><Button type="button" variant="ghost" onClick={resetForm} className="rounded-full">Cancel</Button></div></form>}
    <div className="mt-8 grid gap-5 lg:grid-cols-2">{restaurants.isLoading ? Array.from({ length: 2 }).map((_, index) => <div key={index} className="h-64 animate-pulse rounded-3xl bg-[#e6dfd6]" />) : restaurants.data?.map(restaurant => <article key={restaurant.id} className="rounded-3xl border border-[#e4ddd2] bg-[#fbf9f5] p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-[#8b7560]">QRServe managed venue</p><h2 className="mt-3 font-display text-3xl text-[#201d19]">{restaurant.name}</h2><p className="mt-2 flex items-center gap-2 text-sm text-[#70675d]"><MapPin className="h-4 w-4 text-[#ed5739]" />{restaurant.location}</p></div><button onClick={() => { if (confirm(`Remove ${restaurant.name}? This also removes its menu and analytics.`)) remove.mutate({ id: restaurant.id }); }} aria-label={`Remove ${restaurant.name}`} className="rounded-xl p-2 text-[#9a8d7c] transition hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div><p className="mt-6 min-h-12 text-sm leading-6 text-[#70675d]">{restaurant.description || "No public description yet. Add one before the table card is printed."}</p><div className="mt-6 flex flex-wrap gap-2"><Button onClick={() => setLocation(`/app/menu/${restaurant.id}`)} className="rounded-full bg-[#201d19] text-white hover:bg-[#3a342e]"><UtensilsCrossed className="mr-2 h-4 w-4" />Prepare menu</Button><Button onClick={() => setLocation(`/app/qr/${restaurant.id}`)} variant="outline" className="rounded-full border-[#d8cfc3] bg-transparent"><QrCode className="mr-2 h-4 w-4" />Table cards</Button><Button onClick={() => { setEditingId(restaurant.id); setName(restaurant.name); setLocationText(restaurant.location); setDescription(restaurant.description || ""); setShowForm(true); }} variant="ghost" className="rounded-full"><Pencil className="mr-2 h-4 w-4" />Edit venue</Button></div></article>)}</div></div></DashboardLayout>;
}
